sudo: false
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DEPS=release
  - DEPS=devel
install:
  - pip install -U pip setuptools
  - '[[ "$DEPS" == "devel" ]] && pip install git+https://github.com/pallets/flask.git || :'
  - pip install -U pytest pytest-cov pytest-mock pytest-pep8 coveralls
  - '[[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] && pip install flask-wtf python-ldap || :'
  - pip install -e .
script:
  - pytest --pep8
after_success:
  - coveralls
notifications:
  email: false
