sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DEPS=release
  - DEPS=devel
install:
  - '[[ "$DEPS" == "devel" ]] && pip install git+https://github.com/pallets/flask.git || :'
  - pip install -U pytest pytest-cov pytest-mock pytest-pep8 coveralls
  - '[[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] && pip install flask-wtf python-ldap || :'
script:
  - python setup.py develop
  - pytest --pep8
after_success:
  - coveralls
notifications:
  email: false
